---
apiVersion: v1
kind: application
metadata:
  name: devtest.service-time
  commType: http
spec:
  services:
    - serviceName: service-time
      components:
        - componentName: service-time
          imageType: docker
          imageName: service-time
          httpPort: 10002
          interfaces:
            - interfaceName: context1
              interfaceType: http
              upstreamPath: /time
              visiblity: external
              accessList:
                - app@client
            - interfaceName: service-time-network
              interfaceType: network
              interfacePort: 10007
              scheme: udp
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
